class SightingsController < ApplicationController
  def show
    sighting = Sighting.find(params[:id])
    #render json: sighting.to_json(:include => {:bird => {:only =>[:name, :species]}, :location => {:only =>[:latitude, :longitude]}}, :except => [:updated_at])
    
    #Serializers generated by the Fast JSON API gem have two built-in methods called serializable_hash 
    #and serialized_json which return a serialized hash and a JSON string respectively
    #render json: SightingSerializer.new(sighting)

  #Now that we have included relationships connecting the SightingSerializer to :bird and :location, 
  #to include attributes from those objects, the recommended method is to pass in a second options 
  #parameter to the serializer indicating that we want to include those objects but this is loated in
  #controller
  options = {
    include: [:bird, :location]
  }
  render json: SightingSerializer.new(sighting, options)
  end

  def index
    sightings = Sighting.all
    render json: SightingSerializer.new(sightings)
  end
end
